### ISSUE TITLE
DINet training

### ISSUE THREAD

**Issue by mldev-stack** [mldev-stack/enhanced_wav2lip#109]

**Comment by angel-yi** [comment]
New directions?

**Comment by primepake** [comment]
aim to build open source that can be using for face talking head

**Comment by tailangjun** [comment]
When do you think it will be ready?

**Comment by mldev-stack** [comment]
maybe the end of this week

**Comment by tailangjun** [comment]
> maybe the end of this week

Thank you very much

**Comment by tailangjun** [comment]
Great guy, is the development going smoothly?
